"plate_diam"= 4
"magnet_thickness"= 0.125
"coupling_diam"= 2.5
"ball_diam"= .375
"dowel_diam"= 0.25
"plate_thickness"= 0.47
"D1@Sketch1"="plate_diam"
"D1@baseplate" = "plate_thickness"
"magnet_diam"=1.26
"D1@Sketch3"="magnet_diam"+"magnet_radial_tol"
"D1@magnet_inset" = "magnet_thickness" + "glue_thickness"
"glue_thickness"= 0.005
"magnet_radial_tol"= 0.0025
"dowel_length"= .75
"D1@Sketch4"="dowel_length"+0.01
"dowel_center_to_center" = 2 * ( sqr ( ( ( ( "dowel_diam" + "ball_diam" ) / 2 ) ^ 2 ) / 2 ) )
"dowel_slot_width"= "dowel_center_to_center" + "dowel_diam"
"D2@Sketch4"="dowel_slot_width"
"D1@coupling_circle" = "coupling_diam"
"dowel_slot_depth" = "dowel_diam" * 0.75
"D1@dowel_slot" = "dowel_slot_depth"
"corner_relief_diam"= 0.25
"D1@Sketch6"="corner_relief_diam"
"central_hole_diam"= 0.5
"D1@Sketch7"="central_hole_diam"
"ball_center_to_slot_bottom"= ( "dowel_center_to_center" / 2 ) + ( "dowel_diam" / 2 )
"total_coupling_height"= 1
"ball_embed_depth"= 0.15
"ball_hole_diam"= 2 * sqr ( ( "ball_diam" / 2 ) ^ 2 + - ( "ball_diam" / 2 - "ball_embed_depth" ) ^ 2 )
"total_stack_height"= "plate_thickness" - "dowel_slot_depth" + "ball_center_to_slot_bottom" + ( "ball_diam" / 2 ) - "ball_embed_depth" + "plate_thickness"
